import {TrpcProvider} from "./TrpcProvider";
import {ClerkProvider} from "@clerk/nextjs";
import "@uploadthing/react/styles.css";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// here we wrap all of our pages with TrpcProvider to enable the client to invoke RPCs

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <TrpcProvider>
        <ClerkProvider>
          <html lang="en">
          <head></head>
          <body>
          {children}
          </body>
          </html>
        </ClerkProvider>
      </TrpcProvider>
  )
}
